### PR TITLE
closes #425

### LINKED ISSUE #425: Product Image does not show on abandoned cart email template / order details
### Preconditions

There is no product image for order or abandoned cart email shown for a simple / configurable products combination in case of images are stored on configurable level.  

Example:

    1. Magento CE 2.2.3 without sample data is installed.
    2. mc-magento2 1.0.29

### Steps to reproduce

    1. Create an order using a configurable product where images stored on configurable level.
    2. Order is pushed to Mailchimp
    3. Look into order details, image url is empty

### Actual and Expected result

    Expected result:
    - See an image for the product in mailchimp

    Actual result:
    - No image is shown

### PR DESCRIPTION
**Pull request by gonzaloebiz**

### CODE REVIEW

**Review by SantiParagarino — APPROVED** [review]

File: Model/Api/Product.php [hunk 1]
```diff
@@ -383,31 +388,23 @@ protected function _buildProductData(
...
-                    }
-                    if ($tailUrl!='') {
-                        break;
+                        $tailUrl .= $option['attribute_code'] . "=" . $product->getData($option['attribute_code']);
                     }
                 }
                 if ($parent) {
                     $this->_childtUrl = $data['url'] = $parent->getProductUrl() . $tailUrl;
-                    if(!isset($data['image_url'])) {
+                    if(!isset($data['image_url'])||$data['image_url']=='') {
```
Comment (maximbaibakov) [inline Model/Api/Product.php:407]: "empty" function is way to use here, instead of these two conditions.

File: Model/Api/Product.php [hunk 2]
```diff
@@ -340,18 +340,23 @@ protected function _buildProductData(
...
 
         //data applied for both root and varient products
         $data["id"] = $product->getId();
         $data["title"] = $product->getName();
         $data["url"] = $product->getProductUrl();
-        if ($product->getImage()) {
+        if ($product->getImage()&&$product->getImage()!='no_selection') {
             $filePath = 'catalog/product'.$product->getImage();
             $data["image_url"] = $this->_helper->getBaserUrl($magentoStoreId, \Magento\Framework\UrlInterface::URL_TYPE_MEDIA).$filePath;
         } elseif ($this->_parentImage) {
```
Comment (maximbaibakov) [inline Model/Api/Product.php:352]: $this->_parentImage should be removed or the logic should be changed, as line 431 could result in empty image in some case. 

if (isset($data['image_url'])) {
  $this->_parentImage = $data['image_url'];
}

OR the condition on this should be changed to use empty function instead of isset

**Comment by maximbaibakov** [comment]
Hi @gonzaloebiz 

I have put a few comments around this PR.
Could you please have a look? 

Regards,
Maxim
