### PR TITLE
closes #2003 for magento 2.1

### LINKED ISSUE #2003: Manage deleted and not salable products
### Preconditions

    1. Any version of magento with sample data .
    2. Any version of mc-magento2 installed and configured
    3. Wait until the store is completely synced

### Steps to reproduce

Case 1:

    1. Try to disable one product
    2. Wait until the product syncs

Case 2:

    1. Re enable a disable product
    2. Wait until the product syncs

Case 3:

    1. Try to delete one product
    2. Wait until the product syncs

### Actual and Expected result

    Expected result:
    If the product is disabled or deleted, the product must not be available for recommendations or any other thing
    Actual result:
   The product remains available in mailchimp

### PR DESCRIPTION
**Pull request by gonzaloebiz**

### CODE REVIEW

File: Helper/Sync.php [hunk 1]
```diff
@@ -101,6 +101,10 @@ public function markEcommerceAsDeleted($relatedId, $type, $relatedDeletedId = nu
     {
         $this->chimpSyncEcommerce->markAllAsDeleted($relatedId, $type, $relatedDeletedId);
     }
+    public function markEcommorceAsNotDeleted($relatedId, $type)
+    {
+        $this->chimpSyncEcommerce->markEcommorceAsNotDeleted($relatedId, $type);
+    }
```
Comment (agustinbv) [inline Helper/Sync.php:107]: Change to this:
```suggestion
    public function markEcommerceAsNotDeleted($relatedId, $type)
    {
        $this->chimpSyncEcommerce->markEcommerceAsNotDeleted($relatedId, $type);
    }
```

**Review by federicocanedo — APPROVED** [review]
