### PR TITLE
closes #1288 for magento 2.1

### LINKED ISSUE #1288: Incorrect image url with some extensions (p.e. cloudinary extension)
Some image extensions don't fit the Magento way and return the image path without the preceding /, this cause that when we fill the product image to sync the URL is wrong

### PR DESCRIPTION
**Pull request by gonzaloebiz**

### CODE REVIEW

**Review by Juan-ebizmarts — APPROVED** [review]

File: Model/Api/Product.php [hunk 1]
```diff
@@ -379,14 +379,14 @@ protected function _buildProductData(
...
-            $filePath = 'catalog/product'.$product->getImage();
+            $filePath = 'catalog/product/'.ltrim($product->getImage(), '/');
             $data["image_url"] = $this->_helper->getBaserUrl($magentoStoreId, \Magento\Framework\UrlInterface::URL_TYPE_MEDIA).$filePath;
         } elseif ($this->_parentImage) {
             $data['image_url'] = $this->_parentImage;
         } else {
             $parent = $this->_getParent($product->getId(), $magentoStoreId);
             if ($parent && $parent->getImage() && $parent->getImage()!='no_selection') {
-                $filePath = 'catalog/product'.$parent->getImage();
+                $filePath = 'catalog/product'.ltrim($parent->getImage(), '/');
```
Comment (waynetheisinger) [inline Model/Api/Product.php:389]: Hi @gonzaloebiz - you've missed the slash off the end of `catalog/product` it should be:

```
$filePath = 'catalog/product/'.ltrim($parent->getImage(), '/');
```

**Review by waynetheisinger — COMMENTED** [review]
I Spotted a typo see below:
